### ISSUE TITLE
how to download more past data 

### ISSUE THREAD

**Issue by augmen** [lewisdonovan/google-news-scraper#1]
how to make it work to download past 5 years data for particular search word ??

**Comment by lewisdonovan** [comment]
> how to make it work to download past 5 years data for particular search word ??

The Google News search results page allows filtering by URL query params, so I could add a command line option to pass this into the URL. 

That said, it looks like there's a limit to the number of results it will serve in a single page, even after scrolling for lazy-loaded results, so I'm not sure there's a programmatic way of pulling everything for such a long time period.

This tool isn't intended as a deep application integration, but rather a quick way to pull latest news for a given topic. You might be better off subscribing to an API such as [The Press Association](http://developer.press.net/) and pulling results that way.

**Comment by lewisdonovan** [comment]
Solved in latest commit
https://github.com/lewisdonovan/google-news-scraper/commit/d25ab908a8fff528bc65b29639e6090784ca147c#diff-1fdf421c05c1140f6d71444ea2b27638
