### ISSUE TITLE
I don't get any news

### ISSUE THREAD

**Issue by ExpErgio** [lewisdonovan/google-news-scraper#11]
I don't get any news:
```js
const googleNewsScraper = require('google-news-scraper')

async function main(){
  let articles = await googleNewsScraper({
      searchTerm: "Cuba",
      prettyURLs: false,
      timeframe: "5d",
      puppeteerArgs: []
  })
  console.log(articles)
}

main();
```

Console:
```
[]
```

**Comment by lewisdonovan** [comment]
Hi @ExpErgio 

I've run this code snippet locally and it return results as expected. Could you tell me some more about your setup and environment, and provide an error log?

**Comment by lewisdonovan** [comment]
I'm going to close this ticket, as it hasn't received a reply in 3 months. If you're still facing issues, please open a full ticket with more information about your setup and any error messages, and I'll be happy to help.
