### ISSUE TITLE
Pretty URLS

### ISSUE THREAD

**Issue by hakizimana-fred** [lewisdonovan/google-news-scraper#12]
when pretty urls argument is set to true, the following error occurs: failed, reason: read ECONNRESET

**Comment by lewisdonovan** [comment]
Hi Fred,
I've run the `test.js` file locally on my machine, everything is working fine and I'm unable to reproduce the error. The error may be originating from something else in your setup. Can you provide some code for your use case, and a full error log?

**Comment by hakizimana-fred** [comment]
getTrend: async function (req, res) {
    try {
      const articles = await googleNewsScraper({
        searchTerm: req.query.keyword,
        prettyURLs: true,
        timeframe: "1d",
        puppeteerArgs: ["--no-sandbox", "--disable-setuid-sandbox"],
      });
      return res.status(200).json(articles);
    } catch (err) {
      console.log(err.message);
    }
  },
hey there above is my code
