### ISSUE TITLE
Subtitle on all artilces is "bookmark_border"

### ISSUE THREAD

**Issue by maorkavod** [lewisdonovan/google-news-scraper#14]
why can i see the real subtitle?

thank you

**Comment by lewisdonovan** [comment]
Hi @maorkavod, 
Unfortunately Google have removed subtitles from the markup, so we can no longer scrape them. I've removed this property from the results object in fa78f9e41f0b53d4ba936ff129064ae08a9bf416. 

Thanks for flagging!
