### ISSUE TITLE
there is any chance to crawl also "topics" ? 

### ISSUE THREAD

**Issue by maorkavod** [lewisdonovan/google-news-scraper#15]
Page like this URL : 

https://news.google.com/topics/CAAqJggKIiBDQkFTRWdvSUwyMHZNRFp1ZEdvU0FtbDNHZ0pKVENnQVAB?hl=he&gl=IL&ceid=IL%3Ahe

**Comment by lewisdonovan** [comment]
This was added in 4c6a0769b6b15ffa80860eac8e18ec61682b638e
