### ISSUE TITLE
Just a doubt ! hope you can help !

### ISSUE THREAD

**Issue by ujjwal-kr** [lewisdonovan/google-news-scraper#2]
[x] question
Hi, I really liked your approach.....
BUT WONT GOOGLE NEWS BLOCK MY IP IF I SCRAPE THEIR CONTENT ??

**Comment by lewisdonovan** [comment]
It's very unlikely, as we're using a headless browser instance - it looks like a human visitor. You'd have to be doing an incredibly high volume of concurrent requests to actually get your IP blocked by Google.

However, there are a few steps that can be taken to help prevent this. I'll add them in a future release.

**Comment by ujjwal-kr** [comment]
Thanks !

**Comment by lewisdonovan** [comment]
Changes have been made in the latest commit
https://github.com/lewisdonovan/google-news-scraper/commit/3ee797a737ab9248956df513fee247f1f75442ed
