### ISSUE TITLE
Add Actual date object to response

### ISSUE THREAD

**Issue by mashegoindustries** [lewisdonovan/google-news-scraper#21]
The time field is human readable, I am happy with that. 
My question is is it possible to include an actual date object in the response, maybe call it **publishedAt**

    {
        "title":  "Article title",
        "subtitle":  "Article subtitle",
        "link":  "http://url-to-website.com/path/to/article",
        "image":"http://url-to-website.com/path/to/image.jpg",
        "source":  "Name of publication",
        "time":  "Time/date published (human-readable)",
        **### "publishedAt": "2022-01-10T09:38:15Z",**
    }

**Comment by lewisdonovan** [comment]
Hi @mashegoindustries great question! Unfortunately we can only take what is available in the markup and, at the time the module was last updated, there was no full timestamp available. I will check again each time I make any changes to the module, but until the data is there we can't add it.
