### ISSUE TITLE
import of node-fetch throws an error [ERR_REQUIRE_ESM] while during runtime

### ISSUE THREAD

**Issue by sv-shivansh** [lewisdonovan/google-news-scraper#26]
Attatched is the error message what comes everytime while trying to run the code.
<img width="743" alt="Screenshot 2022-05-12 at 5 23 50 PM" src="https://user-images.githubusercontent.com/56015329/168069023-d6edc1c9-1a02-47b1-aa52-bf584e0a085b.png">

**Comment by mashegoindustries** [comment]
@sv-shivansh 

Same issue. Can you share branch name.

I want to use it whilst we wait for this to be merged.

My customer facing App stopped working.

**Comment by sv-shivansh** [comment]
@mashegoindustries Yeah!!! https://github.com/sv-shivansh/google-news-scraper You can view the changes in the given branch.

**Comment by lewisdonovan** [comment]
Fixed in #27 thank you @sv-shivansh 🙏
