### ISSUE TITLE
Use as an API?

### ISSUE THREAD

**Issue by MrUltimate** [lewisdonovan/google-news-scraper#3]
Hi,

How can I incorporate this into a react app I'm building? I'd ideally like to get the JSON results and do some machine learning tasks on the returned data. Would you be able to make this into a node library that would return JSON data when called?

Also, is there a way to get results from the homepage? Kind of like a top headlines/latest news selection.

Thanks!

**Comment by lewisdonovan** [comment]
Great idea! I've amended the repo so the module now returns the array of article objects.
