### ISSUE TITLE
Premature close

### ISSUE THREAD

**Issue by hakizimana-fred** [lewisdonovan/google-news-scraper#31]
Hello!
When I tried to utilize this package to get news off google I had this weird response
Invalid response body while trying to fetch https://news.google.com/articles/CBMiSWh0dHBzOi8vdGFzdGVvZmNvdW50cnkuY29tL25vYWgtdGhvbXBzb24taHVudGVyZ2lybC1vbmUtZGF5LXRvbmlnaHQtaWRvbC_SAQA?hl=en-US&gl=US&ceid=US%3Aen: Premature close
 Hoping you can look into it. thanks, plus the package breaks on higher version of nodejs 14. I always had to use import statements in the nodemodules,
Regards
Fred

**Comment by reda85** [comment]
I have the same error when deploying in Vercel (Node version 14 and higher)

**Comment by hakizimana-fred** [comment]
I actually submitted a PR that intends to solve Version issues, it's mostly likely he hasn't seen it yet, hopefully he does merge it soon

**Comment by reda85** [comment]
It has been merged, waiting for the npm package.
Thanks to all.

**Comment by hakizimana-fred** [comment]
Awesome!

**Comment by lewisdonovan** [comment]
Thanks @hakizimana-fred, I've merged your PR in #32 and published to NPM. Closing this ticket.
