### ISSUE TITLE
Image fundamental change

### ISSUE THREAD

**Issue by mashegoindustries** [lewisdonovan/google-news-scraper#39]
I don't know if its only on my side, but the image is not coming through as it use to.
Perhaps another fundamental change in the markup on the Google News site

All other fields are not affected, only image. 
Image is coming though as the below, no https protocol
/api/attachments/******

example

[
    {
        "title":  "Article title",
        "subtitle":  "Article subtitle",
        "link":  "http://url-to-website.com/path/to/article",
        **"image":"/api/attachments/CC8iK0NnNDRPVmRIZFVWYVIxaEViSFZGVFJDdEFSaWlBaWdCTWdZQk1vck5sUWs=-w400-h224-p-df-rw"**,
        "source":  "Name of publication",
        "time":  "Time/date published (human-readable)"
    }
]

**Comment by ericelizes** [comment]
I ran into this problem too :(

**Comment by kurt-hu** [comment]
Found a quick fix: Prepending https://news.google.com to the /api/... image url that is returned seems to work.

**Comment by lewisdonovan** [comment]
@kurt-hu Thanks for the patch, your fix was added in [a1d2b03](https://github.com/lewisdonovan/google-news-scraper/commit/a1d2b036357d923f45eea1dbf7c34736d7a81752). Please update to latest (1.1.5).

@mashegoindustries @ericelizes1 👀
