### ISSUE TITLE
Config ignored?

### ISSUE THREAD

**Issue by Ciao121** [lewisdonovan/google-news-scraper#47]
Hi,
I'm using it like this:
`const articles = await googleNewsScraper({ searchTerm: "The Oscars"});`
but whatever term I use it seem to ignore it: "SCRAPING NEWS FROM: https://news.google.com/search"
I also tried
`await googleNewsScraper({ "searchTerm": "The Oscars", puppeteerHeadlessMode: false });`
But puppeteer doe not appear. Seems config is ignored. Any idea?

Full script:
**const googleNewsScraper = require("google-news-scraper");
scrapeGoogle()
async function scrapeGoogle(){
	const articles = await googleNewsScraper({ "searchTerm": "Roma", puppeteerHeadlessMode: false });
	console.log(articles)
}**

**Comment by lewisdonovan** [comment]
Hi @Ciao121, I’m moving house at the moment so give me a couple of days and I will look into this for you.

**Comment by lewisdonovan** [comment]
Fixed in 7e8ba2c
