### ISSUE TITLE
Vercel Support

### ISSUE THREAD

**Issue by 0xSaurabhx** [lewisdonovan/google-news-scraper#49]
This module doesn't work on vercel, when i tried host it. 
Any solution to this issue then let me know.

**Comment by lewisdonovan** [comment]
Hi @0xSaurabhx, this is a known issue related to limitations on Vercel free tier. I investigated previously and unfortunately it’s not feasible to fix, although I’m happy to review any PRs that address it.

See #41 for more details.

Closing this ticket for now.
