### ISSUE TITLE
prettyURLs not working as expected. (in the latest release v1.2.5)

### ISSUE THREAD

**Issue by sainiankit** [lewisdonovan/google-news-scraper#54]
link in results seem to be always https://news.google.com/read/xxxxx, even with prettyURLs set to true

**Comment by lewisdonovan** [comment]
Previously we could simply extract the pretty URL from the ugly URL as a base64 string, but it looks like Google have changed the way these strings are formed. 

@anthonyfranc did a great job finding this previously, not sure if he'd be up for taking a look at this again?

I did also try following the redirect, but it looks like Google have put a captcha page in between the redirect, and I'm not sure adding a captcha solver just to grab the URLs has sufficient time-cost/benefit at this point.

Let's keep this issue open and see what the community says.

**Comment by anthonyfranc** [comment]
> Previously we could simply extract the pretty URL from the ugly URL as a base64 string, but it looks like Google have changed the way these strings are formed.
> 
> @anthonyfranc did a great job finding this previously, not sure if he'd be up for taking a look at this again?
> 
> I did also try following the redirect, but it looks like Google have put a captcha page in between the redirect, and I'm not sure adding a captcha solver just to grab the URLs has sufficient time-cost/benefit at this point.
> 
> Let's keep this issue open and see what the community says.

I'll take a look and see what I can find, thanks for the heads up!

**Comment by ankittchaurasia** [comment]
After looking through the network console and reverse engineering, this works, but it's still a pain as sometimes it might get blocked and will take extra time for fetching HTML and sending requests. If someone really wants to get the URL, they should use a proxy and pass it in Axios to avoid getting rate limited.

```javascript
import axios from 'axios';
import { load } from 'cheerio';

async function getGoogleNewsRssFinalUrl(url){
    const parsedUrl = new URL(url);
    const gnArticleId = parsedUrl.pathname.split('/').pop();
    const { data: gnData } = await axios.get(`https://news.google.com/articles/${gnArticleId}`);

    const $ = load(gnData);
    const div = $('c-wiz > div').first();
    const article = {
      signature: div.attr('data-n-a-sg'),
      timestamp: div.attr('data-n-a-ts'),
      gn_art_id: gnArticleId,
    };

    const articlesReq = [
      'Fbv4je',
      `["garturlreq",[["X","X",["X","X"],null,null,1,1,"US:en",null,1,null,null,null,null,null,0,1],"X","X",1,[1,1,1],1,1,null,0,0,null,0],"${article.gn_art_id}",${article.timestamp},"${article.signature}"]`,
    ];

    const response = await axios.post(
      'https://news.google.com/_/DotsSplashUi/data/batchexecute',
      new URLSearchParams({ 'f.req': JSON.stringify([[articlesReq]]) }).toString(),
      {
        headers: { 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8' }
      },
    );

    const urlstring =  JSON.parse(JSON.parse(response.data.split('\n\n')[1].slice(0))[0][2])[1];
    console.log(urlstring);
    return urlstring;
  }
  
    getGoogleNewsRssFinalUrl("https://news.google.com/rss/articles/CBMikAFBVV95cUxNWWxmSlJzRmxtRnRfNW52U3RET2NHbllWSkZPamJ3TjFkLTE5M3p2VEFsN2xpY3JZNzlWRmlXTl91MWNvWVRaMlllbVU0Nk9hbUV0MExYamdSZFRFeThpWTJhYW5YRUdiTkQxRU15Sm1fcmpvMXlhS2x2WGFFd3dYTFByaU0tUlJZbmpud2trdEPSAYcBQVVfeXFMUHpURUkwTzg4N2s5M2l3RUp5SVBWamUzbEFydjVyb0JJUlRMRWZaeE1CbjJ5eUVxTXh1STc3NGhvcnRmeXRDMWtCTVU4X2hGczRHZXItc1E5ODJMdkMzRmNNX0FIVzBZUm5CNklGb2pXTTBJdUZVby1sQWw5cFRPekZjMXE4ZU9n?oc=5")
```

**Comment by lewisdonovan** [comment]
Closing this as wontfix, because there doesn't seem to be a reasonable programmatic workaround. As mentioned by @ankittchaurasia, users looking for a solution should use a proxy.

**Comment by CodeVisionEvgen** [comment]
+
