### ISSUE TITLE
Parsing latest news

### ISSUE THREAD

**Issue by CodeVisionEvgen** [lewisdonovan/google-news-scraper#57]
Is it possible to get the latest news

**Comment by lewisdonovan** [comment]
It gets the articles that Google News gives you for the topic you search for. You can limit the timeframe (using the `timeframe` parameter in the config) to ensure you only get results for the time period you want. 

If you wanted only very recent news you could set it to `1h`, to only return results published in the last hour.

**Comment by CodeVisionEvgen** [comment]
Are there limits on the number of requests?

**Comment by CodeVisionEvgen** [comment]
Are there limits on the number of requests?

**Comment by lewisdonovan** [comment]
The package itself doesn't impose any limits, but obviously excessive use will probably cause Google to gate requests from your session or IP with a captcha or similar. If you're running it in the cloud, you'd also need to be aware of the usage costs or limit that your cloud provider stipulates. But the package itself does not impose any limits.
